# Generated by Django 5.1.2 on 2024-11-02 21:01

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from bookshelf.models import Post

def create_groups_and_permissions(apps, schema_editor):
    # Create Groups
    viewer_group, created = Group.objects.get_or_create(name='Viewers')
    editor_group, created = Group.objects.get_or_create(name='Editors')
    admin_group, created = Group.objects.get_or_create(name='Admins')

    # Assign Permissions
    can_view = Permission.objects.get(codename='can_view', content_type__model='post')
    can_create = Permission.objects.get(codename='can_create', content_type__model='post')
    can_edit = Permission.objects.get(codename='can_edit', content_type__model='post')
    can_delete = Permission.objects.get(codename='can_delete', content_type__model='post')

    # Assign Permissions to Groups
    viewer_group.permissions.add(can_view)
    editor_group.permissions.add(can_create, can_edit)
    admin_group.permissions.add(can_view, can_create, can_edit, can_delete)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name= 'CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/', null=True, blank=True)),
            ],
        ),

        migrations.RunPython(create_groups_and_permissions),
    ]